### ISSUE TITLE
Gamemode support

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/com.atlauncher.ATLauncher#4]
Enable gamemode support

**Comment by Doomsdayrs** [comment]
Likely with the following

```yaml
- name: gamemode
    buildsystem: meson
    config-opts: &gamemode_opts
      - -Dwith-systemd=false
      - -Dwith-daemon=false
      - -Dwith-examples=false
      - -Dwith-util=false
      - -Dwith-sd-bus-provider=no-daemon
    sources: &gamemode_sources
      - type: archive
        url: https://github.com/FeralInteractive/gamemode/releases/download/1.6.1/gamemode-1.6.1.tar.xz
        sha256: 10c2a3f142eae472f5a09e42616e38c666c05b25ca3e61e562a543bb3fda66c5

  - name: gamemode-32bit
    build-options:
      arch:
        x86_64: *compat_i386_opts
    buildsystem: meson
    config-opts: *gamemode_opts
    sources: *gamemode_sources

  - name: gamemoderun
    buildsystem: simple
    build-commands:
      - install -Dm755 data/gamemoderun -t /app/bin
    sources: *gamemode_sources
    ```
